### ISSUE TITLE
能否支持角色管理相关功能

### ISSUE THREAD

**Issue by Appleamanda** [jsvnadmin/jsvnadmin#2]
在现有admin和普通用户基础上，增加自定义角色，以实现不同角色的管理用户查看不同的普通用户、项目等。
举例：
A管理用户角色为role1，则A用户仅能查看、维护属于role1管理的项目、用户。
B管理用户角色为role2，则B用户仅能查看、维护属于role2管理的项目、用户。
A管理用户和B管理用户无法互相查看、维护。

**Comment by jsvnadmin** [comment]
现在默认超级管理员是所有功能，项目的manager组用户，是管理本项目的。你可以试试。
