### ISSUE TITLE
请问可以控制新建用户时，密码手动加密吗?

### ISSUE THREAD

**Issue by HuberyYan** [jsvnadmin/jsvnadmin#6]
现在面临一个问题就是，SVN服务端本身创建用户和密码时，配置文件中会添加加密后的密码。
现在想在代码中新建用户，应该如何给密码加密
延展问题：如何对加密的密码进行解密

**Comment by jsvnadmin** [comment]
解压这个class替换掉（\WEB-INF\lib\svnadmin-x.x.x.jar\org\svnadmin\util\EncryptUtil.class)
[EncryptUtil.zip](https://github.com/jsvnadmin/jsvnadmin/files/4173660/EncryptUtil.zip)

，数据库保存的用户密码就是明文密码，然后在页面上项目点一下保存，就会重新输出配置文件，你试试。
